

/*  CREDIT CARD TRANSACTIONS DATA ANALYSIS  */  


-- Fetch the records from credit_card_transaction.

SELECT *
FROM CREDIT_CARD_TRANSACTION
ORDER BY ID_NO;

-- Fetch the unique city names which have serviced credit card.

SELECT DISTINCT CITY
FROM CREDIT_CARD_TRANSACTION;

-- Find the year. in which years transactions are generated.

SELECT DISTINCT EXTRACT(YEAR FROM date) AS YEARS
FROM CREDIT_CARD_TRANSACTION
ORDER BY YEARS;

-- Fetch the types of Card Categories:

SELECT DISTINCT CARD_TYPE
FROM CREDIT_CARD_TRANSACTION;

-- Find the type of expenses paid by customers.

SELECT DISTINCT EXPENSES_TYPE
FROM CREDIT_CARD_TRANSACTION;

-- Query the total number of transactions done by gender.

SELECT GENDER,
	COUNT(GENDER)
FROM CREDIT_CARD_TRANSACTION
GROUP BY GENDER;

-- Count the card type under city.

SELECT CITY,
	CARD_TYPE,
	COUNT(CARD_TYPE) AS NO_OF_CARD_TYPE
FROM CREDIT_CARD_TRANSACTION
GROUP BY CITY,
	CARD_TYPE
ORDER BY NO_OF_CARD_TYPE DESC;

-- Count the expenses type under card type.

SELECT CARD_TYPE,
	   COUNT(EXPENSES_TYPE) AS NUMBER_OF_EXPENSES_TYPES
FROM CREDIT_CARD_TRANSACTION
GROUP BY CARD_TYPE;

-- Fetch the top 10 city by using card type.

SELECT DISTINCT CITY,
	CARD_TYPE,
	COUNT(CARD_TYPE) OVER (PARTITION BY CITY,
	CARD_TYPE) AS COUNT_OF_CARD_TYPE
FROM CREDIT_CARD_TRANSACTION
ORDER BY COUNT_OF_CARD_TYPE DESC
LIMIT 10;

-- Fetch the city and card name. which city had the highest usage of card types in the year 2014. 

SELECT DISTINCT CITY,
	CARD_TYPE,
	X.COUNT_OF_CARD_TYPE
FROM
	(SELECT CARD_TYPE,
			CITY,
			COUNT(CARD_TYPE) OVER (PARTITION BY CITY,
			CARD_TYPE) AS COUNT_OF_CARD_TYPE
FROM CREDIT_CARD_TRANSACTION  
WHERE EXTRACT(YEAR FROM date) = 2014) X
ORDER BY X.COUNT_OF_CARD_TYPE DESC;

/* Fetch the city,card_type and expenses type. 
Which city has paid highest amount by using card type and print card type to next column */

SELECT CITY,
	CARD_TYPE,
	EXPENSES_TYPE,
	AMOUNT,
	FIRST_VALUE(CARD_TYPE) OVER (PARTITION BY CITY
	ORDER BY AMOUNT DESC) AS TOP_CARD_BY_AMOUNT_PAID
FROM CREDIT_CARD_TRANSACTION; 

-- Query the total number of card type that were used in the year of 2013, 2014 & 2015.

SELECT DISTINCT CARD_TYPE,
	EXTRACT(YEAR
	FROM date) AS YEARS,
	COUNT(CARD_TYPE) OVER (PARTITION BY EXTRACT(YEAR
	FROM date),
	CARD_TYPE) AS COUNT_OF_CARD_TYPE
FROM CREDIT_CARD_TRANSACTION
ORDER BY YEARS;

-- Count the expenses type. Which card type as used to pay highest expenses.

SELECT DISTINCT CARD_TYPE,EXPENSES_TYPE,
	COUNT(EXPENSES_TYPE) OVER (PARTITION BY CARD_TYPE,
    EXPENSES_TYPE) AS COUNT_OF_EXPENSES
FROM CREDIT_CARD_TRANSACTION
ORDER BY COUNT_OF_EXPENSES DESC;  

-- Query the total amount of card type.

SELECT DISTINCT CARD_TYPE,
	SUM(AMOUNT) OVER (PARTITION BY CARD_TYPE) AS TOTAL_AMOUNT
FROM CREDIT_CARD_TRANSACTION;

-- Fetch the top 10 city by paying highest amount through card type.

SELECT CITY,
	AMOUNT,
	CARD_TYPE
FROM CREDIT_CARD_TRANSACTION
ORDER BY AMOUNT DESC
LIMIT 10;

-- Query the total amount of card type under year.

WITH CTE AS
	(SELECT *,
		EXTRACT(YEAR FROM date) AS YEARS
		FROM CREDIT_CARD_TRANSACTION)
SELECT DISTINCT CARD_TYPE,
    YEARS,
	SUM(AMOUNT) OVER (PARTITION BY CARD_TYPE,YEARS)
FROM CTE
ORDER BY YEARS;

-- Fetch the card types and total expenses amount for the first three quarters of each year.

WITH CTE AS
	(SELECT CARD_TYPE,
			AMOUNT,DATE,
	CASE
		WHEN EXTRACT(MONTH FROM date) BETWEEN 1 AND 4 THEN 'Qtr1'
		WHEN EXTRACT(MONTH FROM date) BETWEEN 5 AND 8 THEN 'Qtr2'
		WHEN EXTRACT(MONTH FROM date) BETWEEN 9 AND 12 THEN 'Qtr3'
	END AS QUARTER_OF_MONTH
		FROM CREDIT_CARD_TRANSACTION)
SELECT DISTINCT CARD_TYPE,
	EXTRACT(YEAR FROM DATE) AS YEAR,
	QUARTER_OF_MONTH,
	SUM(AMOUNT) OVER (PARTITION BY QUARTER_OF_MONTH,
					  CARD_TYPE) AS SUM_OF_AMOUNT 
FROM CTE 
ORDER BY QUARTER_OF_MONTH,YEAR;